### ISSUE TITLE
JPEG2000-RCT transform equations are incomplete / don't match reference

### ISSUE THREAD

**Issue by dwbuiten** [FFmpeg/FFV1#182]
In both RAWCooked and the ffv1dec, the Cr and Cb components first have `1<<bits` subtracted from them (Y does not), but this is not present in the spec.

**Comment by JeromeMartinez** [comment]
I was sure I wrote in the spec that Cr and Cb are positively shifted by half of max value + 1 (so source max value + 1, as Cb and Cr have 1 additional bit) in the bitstream in order to have only non-negative numbers stored, but looks like that the patch was not integrated.
I try to find it in my local repo else I write it again.
