### ISSUE TITLE
questions about the Border section

### ISSUE THREAD

**Issue by dericed** [FFmpeg/FFV1#42]
The border section gives an example table but it doesn't seem to match the description.

For reference:
```
| 0 | 0 |   | 0 | 0 | 0 |   | 0 |
| 0 | 0 |   | 0 | 0 | 0 |   | 0 |
|   |   |   |   |   |   |   |   |
| 0 | 0 |   | a | b | c |   | c |
| 0 | a |   | d |   | e |   | e |
| 0 | d |   | f | g | h |   | h |
```

For the border to the left of the slice it says `samples to the left of the coded slice are identical to the top right sample (if there is one)`. The top right sample of the slice is `a` so with this definition I'd expect to see 

```
| 0 | 0 |   | 0 | 0 | 0 |   | 0 |
| 0 | 0 |   | 0 | 0 | 0 |   | 0 |
|   |   |   |   |   |   |   |   |
| a | a |   | a | b | c |   | c |
| a | a |   | d |   | e |   | e |
| a | a |   | f | g | h |   | h |
```

I think the intended meaning is more like `samples to the left of the coded slice are identical to the sample that is above the sample to the right (if there is one)`; however this isn't quite right either:
```
| 0 | 0 |   | 0 | 0 | 0 |   | 0 |
| 0 | 0 |   | 0 | 0 | 0 |   | 0 |
|   |   |   |   |   |   |   |   |
| 0 | 0 |   | a | b | c |   | c |
| 0 | a |   | d |   | e |   | e |
| a | d |   | f | g | h |   | h |
```

Is there a need for more than one column of border of the left? Is this sufficient?

```
| 0 |   | 0 | 0 | 0 |   | 0 |
| 0 |   | 0 | 0 | 0 |   | 0 |
|   |   |   |   |   |   |   |
| 0 |   | a | b | c |   | c |
| a |   | d |   | e |   | e |
| d |   | f | g | h |   | h |
```

**Comment by dericed** [comment]
ping. Is more than one border column/row needed?

**Comment by JeromeMartinez** [comment]
1/ "The top right sample of the slice is a so with this definition I'd expect to see"

impossible: you can not compute `a` from `a`, as `a` is not yet known. so no copy of `a` on the left of the real `a`
FFmpeg code is:

```C
        sample[1][-1] = sample[0][0];
        sample[0][w]  = sample[0][w - 1];
```

With:
- all 0 as init
- sample[0] is the previous line (full 0 if current line is the first one)
- sample[1] is the current line
- `w` is the width of the plane

--> It is done only once, for pixel 0, not for pixel "-1", so no `a` on the last line on the extreme left.
line 1 sample "-1" is line 0 sample "0"
line 0 sample  "last +1" is line 0 sample "last"
line 1 sample "-2" is always 0 (I would have put `a` too but this is not what is coded)

I don't know how it should be in plain text, but the reference array is correct from my point of view.

Let's try `sample to the left of a first coded sample of a line is identical to the first coded sample of a line that is above (if there is one)`

In practice it would be:
```
| X | X |   | 0 | 0 | 0 |   | X |
| X | 0 |   | 0 | 0 | 0 |   | 0 |
|   |   |   |   |   |   |   |   |
| 0 | 0 |   | a | b | c |   | c |
| 0 | a |   | d |   | e |   | e |
| 0 | d |   | f | g | h |   | h |
```

with `X` impossible cases (never used)

2/ "Is more than one border column/row needed?"

for the moment I did not face a frame with the need of column "-2" and line "-2", but the FFmpeg code is:
```C
    const int LT = last[-1];
    const int T  = last[0];
    const int RT = last[1];
    const int L  = src[-1];

    if (p->quant_table[3][127]) {
        const int TT = last2[0];
        const int LL = src[-2];
        return p->quant_table[0][(L - LT) & 0xFF] +
               p->quant_table[1][(LT - T) & 0xFF] +
               p->quant_table[2][(T - RT) & 0xFF] +
               p->quant_table[3][(LL - L) & 0xFF] +
               p->quant_table[4][(TT - T) & 0xFF];
    } else
        return p->quant_table[0][(L - LT) & 0xFF] +
               p->quant_table[1][(LT - T) & 0xFF] +
               p->quant_table[2][(T - RT) & 0xFF];
```

so if the 128th number of the 4th quant table is not 0, the sample 2 columns before the current column and the sample 2 lines before the current line are used, and for the first pixel of the first column you need 2 borders/rows.

With an array:
```C
if (p->quant_table[3][127])
|   |   |   | 0 |   |
|   | 0 |   | 0 | 0 |
|   |   |   |   |   |
| 0 | 0 |   | a
else
|   |   |   |   |   |
|   | 0 |   | 0 | 0 |
|   |   |   |   |   |
|   | 0 |   | a
```

with `0` values used for computing the context.

So yes, we need more than one border column/row needed (actually 2)?

I think the issue is that the context computing is not yet (well) defined, we should defined it

**Comment by retokromer** [comment]
I didn’t answer, because I can see little pros/cons in both _scenari_, but so far I’m unable to decide.
